/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Data {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'endDate' : Time,
  'createdAt' : Time,
  'discountLabel' : string,
  'description' : string,
  'updatedAt' : Time,
  'startDate' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOffer' : ActorMethod<
    [string, string, string, Time, Time, boolean],
    string
  >,
  'deleteOffer' : ActorMethod<[string], undefined>,
  'getActiveOffers' : ActorMethod<[], Array<Data>>,
  'getAllOffers' : ActorMethod<[], Array<Data>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOffer' : ActorMethod<[string], [] | [Data]>,
  'getOffersFilteredByDateRange' : ActorMethod<[Time, Time], Array<Data>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchOffersByTitle' : ActorMethod<[string], Array<Data>>,
  'toggleOfferActiveState' : ActorMethod<[string], undefined>,
  'updateOffer' : ActorMethod<
    [string, string, string, string, Time, Time, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];